### ISSUE TITLE
Report the needed CKB if transaction failed with insufficient capacity

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-sdk#86]
# Description

![image](https://github.com/sporeprotocol/spore-sdk/assets/3871265/9eec76f7-9878-4ffa-b798-f846d2ae4382)

current information lacks concrete CKB number to prompt developer the potential mistake in estimation transaction CKB cost, for a better development experience, we should enrich our log printings on insufficient capacity occurs.

**Comment by vincentyycheung** [comment]
same errors as my tests:
```
(node:42203) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/CKB/spore-first-example/node_modules/@ckb-lumos/common-scripts/src/common.ts:460
    throw new Error("Not enough capacity in from infos!");
          ^
Error: Not enough capacity in from infos!
    at Object.injectCapacity (/Users/CKB/spore-first-example/node_modules/@ckb-lumos/common-scripts/src/common.ts:460:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async injectNeededCapacity (/Users/CKB/spore-first-example/node_modules/@spore-sdk/core/src/helpers/capacity.ts:240:18)
    at async createSpore (/Users/CKB/spore-first-example/node_modules/@spore-sdk/core/src/api/composed/spore/createSpore.ts:74:38)
    at async main (/Users/CKB/spore-first-example/src/index.ts:9:39)
```
